type Query {
  orders: [Order]!
}

type Order {
  orderId: Int
  userId: Int!
  foodId: Int!
  count: Int!
}

type Mutation {
  createOrder(userId: Int!, foodId: Int!, count: Int!): Response!
  updateOrder(orderId: Int!, userId: Int!, foodId: Int!, count: Int!): Response!
  deleteOrder(orderId: Int!): Response!
}
